In [1]:
# Importing the libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score

In [2]:
# Importing Dataset
dataset = pd.read_csv('indian_liver_patient.csv')
dataset = dataset.dropna(axis = 0)
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [14]:
dataset.describe()

Age  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
count  579.000000       579.000000        579.000000            579.000000   
mean    44.782383         3.315371          1.494128            291.366149   
std     16.221786         6.227716          2.816499            243.561863   
min      4.000000         0.400000          0.100000             63.000000   
25%     33.000000         0.800000          0.200000            175.500000   
50%     45.000000         1.000000          0.300000            208.000000   
75%     58.000000         2.600000          1.300000            298.000000   
max     90.000000        75.000000         19.700000           2110.000000   

       Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
count                579.000000                  579.000000      579.000000   
mean                  81.126079                  110.414508        6.481693   
std                  183.182845                  289.850034        1.084641   
min                   10.000000                   10.000000        2.700000   
25%                   23.000000                   25.000000        5.800000   
50%                   35.000000                   42.000000        6.600000   
75%                   61.000000                   87.000000        7.200000   
max                 2000.000000                 4929.000000        9.600000   

          Albumin  Albumin_and_Globulin_Ratio     Dataset  
count  579.000000                  579.000000  579.000000  
mean     3.138515                    0.947064    1.284974  
std      0.794435                    0.319592    0.451792  
min      0.900000                    0.300000    1.000000  
25%      2.600000                    0.700000    1.000000  
50%      3.100000                    0.930000    1.000000  
75%      3.800000                    1.100000    2.000000  
max      5.500000                    2.800000    2.000000

In [3]:
x

array([[65, 'Female', 0.7, ..., 6.8, 3.3, 0.9],
       [62, 'Male', 10.9, ..., 7.5, 3.2, 0.74],
       [62, 'Male', 7.3, ..., 7.0, 3.3, 0.89],
       ...,
       [52, 'Male', 0.8, ..., 6.4, 3.2, 1.0],
       [31, 'Male', 1.3, ..., 6.8, 3.4, 1.0],
       [38, 'Male', 1.0, ..., 7.3, 4.4, 1.5]], dtype=object)

In [4]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1,
       2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2,

In [5]:
# Encoding Categorical data

labelencoder_x = LabelEncoder()
x[:,1] = labelencoder_x.fit_transform(x[:,1])

In [6]:
x

array([[65, 0, 0.7, ..., 6.8, 3.3, 0.9],
       [62, 1, 10.9, ..., 7.5, 3.2, 0.74],
       [62, 1, 7.3, ..., 7.0, 3.3, 0.89],
       ...,
       [52, 1, 0.8, ..., 6.4, 3.2, 1.0],
       [31, 1, 1.3, ..., 6.8, 3.4, 1.0],
       [38, 1, 1.0, ..., 7.3, 4.4, 1.5]], dtype=object)

In [7]:
# Splitting the dataset into training set and test set

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [8]:
# Fitting Random Forest classifier to the training set

classifier = RandomForestClassifier(n_estimators=100, criterion='entropy',random_state=0)
classifier.fit(x, y)

RandomForestClassifier(criterion='entropy', random_state=0)

In [9]:
#pridicting the output
y_predict=classifier.predict(x_test)
print("\n",r2_score(y_test,y_predict)*100)
print(y_predict)

print(y_test)


 100.0
[2 1 1 2 2 1 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 1 1 1 2 1 1 2 1 1 1 1 2 1 1
 1 1 1 1 1 2 1 1 1 1 1 2 2 1 1 1 1 1 2 1 2 2 1 2 2 1 1 2 1 2 1 1 1 1 2 2 2
 1 1 2 1 1 2 2 2 1 1 1 1 1 1 1 1 2 1 1 2 2 2 2 1 1 2 1 1 1 1 1 1 1 1 2 1 1
 1 2 1 1 1]
[2 1 1 2 2 1 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 1 1 1 2 1 1 2 1 1 1 1 2 1 1
 1 1 1 1 1 2 1 1 1 1 1 2 2 1 1 1 1 1 2 1 2 2 1 2 2 1 1 2 1 2 1 1 1 1 2 2 2
 1 1 2 1 1 2 2 2 1 1 1 1 1 1 1 1 2 1 1 2 2 2 2 1 1 2 1 1 1 1 1 1 1 1 2 1 1
 1 2 1 1 1]


In [10]:
# Applying K-fold cross validation

accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())
accuracies

0.6980111008325623
0.057176266455064476


array([0.59574468, 0.61702128, 0.70212766, 0.73913043, 0.76086957,
       0.7173913 , 0.65217391, 0.7173913 , 0.7826087 , 0.69565217])

In [11]:
#finding accuracy of the pridicted model

Accuracy = r2_score(y_test,y_predict)
print("Accuracy is {} %".format(int(Accuracy*100)))

Accuracy is 100 %


In [12]:
# Pickling the model
import pickle
file = open('liver.pkl','wb')
pickle.dump(classifier,file)